espace_user_homepage:
    path:     /
    defaults: { _controller: EspacePlatformBundle:Default:index }
espace_show_user:
    path:     /user/show
    defaults: { _controller: EspaceUserBundle:User:index }
EU_new_etudiant:
    path:     /etudiant/new
    defaults: { _controller: EspaceUserBundle:Etudiant:n_etudiant }
EU_new_entreprise:
    path:     /entreprise/new
    defaults: { _controller: EspaceUserBundle:Entreprise:n_entreprise }