espace_user_homepage:
    path:     /
    defaults: { _controller: EspacePlatformBundle:Default:index }
espace_show_user:
    path:     /admin/user/show
    defaults: { _controller: EspaceUserBundle:User:show_user }
espace_details_entreprise:
    path:     /entreprise/details/{id}
    defaults: { _controller: EspaceUserBundle:Entreprise:details }
espace_details_candidat:
    path:     /candidat/details/{id}
    defaults: { _controller: EspaceUserBundle:Etudiant:details }
EU_valider_user:
    path:     /admin/user/valider/{id}
    defaults: { _controller: EspaceUserBundle:User:valider_user }
EU_devalider_user:
    path:     /admin/user/devalider/{id}
    defaults: { _controller: EspaceUserBundle:User:devalider_user }
espace_show_register:
    path:     /inscription
    defaults: { _controller: EspaceUserBundle:User:types_profil }
EU_new_etudiant:
    path:     /etudiant/new
    defaults: { _controller: EspaceUserBundle:Etudiant:n_etudiant }
EU_new_entreprise:
    path:     /entreprise/new
    defaults: { _controller: EspaceUserBundle:Entreprise:n_entreprise }
EU_new_alumni:
    path:     /alumni/new
    defaults: { _controller: EspaceUserBundle:Alumni:n_alumni }
EU_new_etudiantCV:
    path:     /candidat/{id}/new/CV
    defaults: { _controller: EspaceUserBundle:Etudiant:edit_CV }
espace_update_user:
    path:     /user/update/{id}
    defaults: { _controller: EspaceUserBundle:User:update_user }
espace_delete_user:
    path:     admin/user/delete/{id}
    defaults: { _controller: EspaceUserBundle:User:delete_user }
EU_create_CV:
    path:     /candidat/{id}/create/CV
    defaults: { _controller: EspaceUserBundle:Etudiant:create_CV }
EU_download_CV:
    path:     /candidat/{id}/download/CV
    defaults: { _controller: EspaceUserBundle:Etudiant:download_Cv }