espace_platform_homepage:
    path:     /
    defaults: { _controller: EspacePlatformBundle:Offre:show_offre }
EP_n_offre:
    path:     /offre/new
    defaults: { _controller: EspacePlatformBundle:Offre:n_offre }
EP_show_offre:
    path:     /offre/show
    defaults: { _controller: EspacePlatformBundle:Offre:show_offre }
EP_update_offre:
    path:     /offre/update/{id}
    defaults: { _controller: EspacePlatformBundle:Offre:update_offre }
EP_delete_offre:
    path:     /offre/delete/{id}
    defaults: { _controller: EspacePlatformBundle:Offre:delete_offre }
EP_search_offre:
    path:     /offre/search
    defaults: { _controller: EspacePlatformBundle:Offre:search_offre }
EP_apply_offre:
    path:     /offre/apply/{id}
    defaults: { _controller: EspacePlatformBundle:Offre:apply }
EP_in_apply_offre:
    path:     /offre/in_apply/{id}
    defaults: { _controller: EspacePlatformBundle:Offre:in_apply }
EP_candidats_offre_show:
    path:     /offre/candidats/{id}/show
    defaults: { _controller: EspacePlatformBundle:Offre:show_candidats }
EP_entro_offre_soumis:
    path:     /offre/soumis/{id}
    defaults: { _controller: EspacePlatformBundle:Offre:soumis }
EP_admin_offre_valider:
    path:     /offre/valider/{id}
    defaults: { _controller: EspacePlatformBundle:Offre:valider }
EP_admin_offre_refuser:
    path:     /offre/refuser/{id}
    defaults: { _controller: EspacePlatformBundle:Offre:refuser }
EP_entro_offre_archiver:
    path:     /offre/archiver/{id}
    defaults: { _controller: EspacePlatformBundle:Offre:archiver }
EP_offre_dupliquer:
    path:     /offre/dupliquer/{id}
    defaults: { _controller: EspacePlatformBundle:Offre:dupliquer }
EP_details_offre:
    path:     /offre/dupliquer/{id}
    defaults: { _controller: EspacePlatformBundle:Offre:details }