# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        Symfony\Component\Security\Core\User\User: bcrypt
        Espace\UserBundle\Entity\User: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_ETUDIANT, ROLE_ENTREPRISE, ROLE_ALUMNI, ROLE_ALLOWED_TO_SWITCH
        ROLE_SUPER_ADMIN: [ ROLE_ADMIN]

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        main:
            entity:
                class: Espace\UserBundle\Entity\User
                property: username
        in_memory:
            memory: 
                users:
                    etudiant:  { password: etudiantpass, roles: [ 'ROLE_ETUDIANT' ] }
                    entreprise:  { password: entreprisepass, roles: [ 'ROLE_ENTREPRISE' ] }
                    alumni:  { password: alumnipass, roles: [ 'ROLE_ALUMNI' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
                    super_admin: { password: super_adminpass, roles: [ 'ROLE_SUPER_ADMIN' ] }

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main_login:
            pattern: ^/(login|etudiant/new|entreprise/new|alumni/new|inscription)$
            anonymous: true
        main:
            pattern:   ^/
            anonymous: false
            provider: main
            switch_user : true
            form_login:
                login_path: login
                check_path: login_check

            logout:
                path: logout
                target: login


            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~


    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
    #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }