<?php

namespace Espace\UserBundle\Repository;

/**
 * AlumniRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlumniRepository extends \Doctrine\ORM\EntityRepository
{
}
