<?php

namespace Espace\PlatformBundle\Repository;

/**
 * Niveau_de_formationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Domaine_de_competenceRepository extends \Doctrine\ORM\EntityRepository
{
}
