<?php

namespace Espace\PlatformBundle\Repository;

/**
 * Secteur_d_activiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Secteur_d_activiteRepository extends \Doctrine\ORM\EntityRepository
{
}
