<?php

namespace Espace\PlatformBundle\Repository;

/**
 * Type_de_contratRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Type_de_contratRepository extends \Doctrine\ORM\EntityRepository
{
}
